"""agregar_sistema_turnos_consultas

Revision ID: 1f3d4e9c722a
Revises: 74ab4cac5859
Create Date: 2025-11-04 10:46:25.692637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3d4e9c722a'
down_revision = '74ab4cac5859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('numero_consulta', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_consultas_turno'), ['turno'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_turno'))
        batch_op.drop_column('numero_consulta')
        batch_op.drop_column('turno')

    # ### end Alembic commands ###
