"""actualizar_especialidades_con_medicos_y_turnos

Revision ID: 578fdd8808b6
Revises: d97093a9a025
Create Date: 2025-11-04 08:19:47.450678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578fdd8808b6'
down_revision = 'd97093a9a025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especialidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_medico', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('especialidad', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('telefono_contacto', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('turno', sa.String(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('ix_especialidades_nombre'))
        batch_op.create_index(batch_op.f('ix_especialidades_nombre_medico'), ['nombre_medico'], unique=False)
        batch_op.drop_column('descripcion')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especialidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_especialidades_nombre_medico'))
        batch_op.create_index(batch_op.f('ix_especialidades_nombre'), ['nombre'], unique=1)
        batch_op.drop_column('turno')
        batch_op.drop_column('telefono_contacto')
        batch_op.drop_column('especialidad')
        batch_op.drop_column('nombre_medico')

    # ### end Alembic commands ###
