"""agregar_sector_y_nivel_conciencia_a_consultas

Revision ID: 74ab4cac5859
Revises: 578fdd8808b6
Create Date: 2025-11-04 09:18:17.891098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ab4cac5859'
down_revision = '578fdd8808b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('nivel_conciencia', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha_cierre', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_consultas_sector'), ['sector'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_sector'))
        batch_op.drop_column('fecha_cierre')
        batch_op.drop_column('nivel_conciencia')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
