"""internados con camas y evoluciones

Revision ID: b0b8300113b7
Revises: 
Create Date: 2025-11-03 06:57:55.396589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b8300113b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internados_codigo_internacion'))
        batch_op.drop_index(batch_op.f('ix_internados_estado'))
        batch_op.drop_index(batch_op.f('ix_internados_fecha_alta'))
        batch_op.drop_index(batch_op.f('ix_internados_fecha_ingreso'))
        batch_op.drop_index(batch_op.f('ix_internados_medico_id'))
        batch_op.drop_index(batch_op.f('ix_internados_paciente_id'))

    op.drop_table('internados')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), nullable=False),
    sa.Column('codigo_internacion', sa.VARCHAR(length=20), nullable=True),
    sa.Column('paciente_id', sa.INTEGER(), nullable=False),
    sa.Column('medico_id', sa.INTEGER(), nullable=False),
    sa.Column('fecha_ingreso', sa.DATETIME(), nullable=False),
    sa.Column('fecha_alta', sa.DATETIME(), nullable=True),
    sa.Column('motivo_internacion', sa.TEXT(), nullable=False),
    sa.Column('diagnostico_ingreso', sa.TEXT(), nullable=False),
    sa.Column('sala', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cama', sa.VARCHAR(length=20), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=30), nullable=True),
    sa.Column('tipo_alta', sa.VARCHAR(length=30), nullable=True),
    sa.Column('evolucion_actual', sa.TEXT(), nullable=True),
    sa.Column('tratamiento_actual', sa.TEXT(), nullable=True),
    sa.Column('observaciones', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internados_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internados_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internados_fecha_ingreso'), ['fecha_ingreso'], unique=False)
        batch_op.create_index(batch_op.f('ix_internados_fecha_alta'), ['fecha_alta'], unique=False)
        batch_op.create_index(batch_op.f('ix_internados_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_internados_codigo_internacion'), ['codigo_internacion'], unique=1)

    # ### end Alembic commands ###
